Repository MIT-Emerging-Talent/ET6-foundations-group-05, pull requests merged in 2025-01, with the labels that each got.

#29 Factorial challenge
  .vscode/settings.json
  solutions/factorial.py
  solutions/tests/test_factorial.py
Labels: challenge

#31 Prime number challenge
  solutions/factorial.py
  solutions/is_prime.py
  solutions/tests/test_factorial.py
  solutions/tests/test_is_prime.py
Labels: challenge

#32 Max profit challenge
  solutions/factorial.py
  solutions/max_profit.py
  solutions/tests/__init__.py
  solutions/tests/test_factorial.py
  solutions/tests/test_max_profit.py
Labels: challenge

#40 enhancement: trying to fix conflict
  .vscode/settings.json
Labels: enhancement

#39 fix config error
  .vscode/settings.json
Labels: enhancement

#42 Palindrome Number Challenge
  solutions/is_palindrome.py
  solutions/tests/test_is_palindrome.py
Labels: challenge

#33 Power of Two Challenge
  solutions/is_power_of_two.py
  solutions/tests/test_is_power_of_two.py
Labels: challenge

#45 Update from Evan: checklist updates post-Q&A
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#46 challenge: Is palindrome challenge
  solutions/is_palindrome.py
  solutions/tests/test_is_palindrome.py
Labels: challenge

#52 New_subtract_two_numbers
  solutions/subtract_two_numbers.py
  solutions/tests/test_subtract_two_numbers.py
Labels: challenge

#48 Challenge/longest substring
  solutions/longest_substring.py
  solutions/tests/test_longest_substring.py
Labels: challenge

#57 Docs/update readme solutions
  solutions/README.md
Labels: documentation

#58 Challenge/fix is power of two formatting
  solutions/is_power_of_two.py
Labels: challenge

#59 Challenge/fix longest substring formatting
  solutions/longest_substring.py
  solutions/subtract_two_numbers.py
Labels: challenge

#61 Docs/update root readme formatting
  README.md
Labels: documentation

#63 Docs/update tests readme
  solutions/tests/README.md
Labels: documentation

#65 Docs: Update Retrospective.md for the /collaboration Folder
  collaboration/retrospective.md
  solutions/is_power_of_two.py
  solutions/longest_substring.py
  solutions/subtract_two_numbers.py
Labels: documentation

#69 docs: update /notes README
  notes/README.md
  notes/command_table.png
  notes/git_commands_guide.md
Labels: documentation

#66 challenge: Even Number Checker
  solutions/is_number_even.py
  solutions/tests/test_is_number_even.py
Labels: challenge

#77 docs: Update the main README.md for solutions table
  README.md
Labels: documentation

#54 challenge: add two integers challenge
  solutions/function_adding_two_integers.py
  solutions/tests/test_function_adding_two_integers.py
Labels: challenge

#79 Even number checker
  solutions/is_number_even.py
  solutions/tests/test_is_number_even.py
Labels: challenge

#80 Update from Evan: module headers, input statements, removed extra words
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#81 docs: Editing the main readme for solution table
  README.md
Labels: documentation

#82 docs: edited some files' name to match perfectly
  README.md
  solutions/adding_two_integers.py
  solutions/single_number.py
  solutions/tests/test_adding_two_integers.py
  solutions/tests/test_single_number.py
Labels: documentation
